[package]
name = "noise_gen"
version = "0.1.0"
edition = "2021"

# [features]
# images = ["image"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.24.5"
noise = "0.8.2"
