[package]
name = "noise_gen"
version = "0.1.0"
edition = "2021"

[features]
default = []
images = ["image", "std"]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
noise = "0.8.2"
image = { version = "0.23", optional = true }
